/** Generated from the pinned headers. Pointer and size arguments use bigint. */
export interface LowLevelFunctions {
  ggml_abs(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_abs_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_acc(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  ggml_acc_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  ggml_add(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_add_cast(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_add_id(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_add_inplace(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_add_rel_pos(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_add_rel_pos_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_arange(arg0: bigint, arg1: number, arg2: number, arg3: number): Promise<bigint>;
  ggml_are_same_shape(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_are_same_stride(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_argmax(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_argsort(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_argsort_top_k(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_backend_alloc_buffer(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_alloc_ctx_tensors(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_alloc_ctx_tensors_from_buft(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_alloc_ctx_tensors_from_buft_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buffer_clear(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_buffer_free(arg0: bigint): Promise<void>;
  ggml_backend_buffer_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_alloc_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buffer_get_base(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_type(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_usage(arg0: bigint): Promise<number>;
  ggml_backend_buffer_init_tensor(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_buffer_is_host(arg0: bigint): Promise<number>;
  ggml_backend_buffer_name(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_reset(arg0: bigint): Promise<void>;
  ggml_backend_buffer_set_usage(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_buft_alloc_buffer(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buft_alloc_buffer_n(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_backend_buft_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_alloc_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buft_get_alloc_size_n(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_backend_buft_get_device(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_is_host(arg0: bigint): Promise<number>;
  ggml_backend_buft_name(arg0: bigint): Promise<bigint>;
  ggml_backend_compare_graph_backend(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<number>;
  ggml_backend_cpu_buffer_from_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_cpu_buffer_type(): Promise<bigint>;
  ggml_backend_cpu_init(): Promise<bigint>;
  ggml_backend_cpu_reg(): Promise<bigint>;
  ggml_backend_cpu_set_abort_callback(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_cpu_set_n_threads(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_cpu_set_threadpool(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_cpu_set_use_ref(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_dev_backend_reg(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_buffer_from_host_ptr(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_backend_dev_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_by_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_by_type(arg0: number): Promise<bigint>;
  ggml_backend_dev_count(): Promise<bigint>;
  ggml_backend_dev_description(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_get(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_get_props(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_dev_host_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_dev_memory(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_dev_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_offload_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_supports_buft(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_supports_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_type(arg0: bigint): Promise<number>;
  ggml_backend_device_register(arg0: bigint): Promise<void>;
  ggml_backend_event_free(arg0: bigint): Promise<void>;
  ggml_backend_event_new(arg0: bigint): Promise<bigint>;
  ggml_backend_event_record(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_event_synchronize(arg0: bigint): Promise<void>;
  ggml_backend_event_wait(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_free(arg0: bigint): Promise<void>;
  ggml_backend_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_get_default_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_get_device(arg0: bigint): Promise<bigint>;
  ggml_backend_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_graph_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_graph_compute_async(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_graph_copy(out: bigint, arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_graph_copy_free(arg0: bigint): Promise<void>;
  ggml_backend_graph_plan_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_graph_plan_create(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_graph_plan_free(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_guid(arg0: bigint): Promise<bigint>;
  ggml_backend_init_best(): Promise<bigint>;
  ggml_backend_init_by_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_init_by_type(arg0: number, arg1: bigint): Promise<bigint>;
  ggml_backend_is_cpu(arg0: bigint): Promise<number>;
  ggml_backend_load(arg0: bigint): Promise<bigint>;
  ggml_backend_load_all(): Promise<void>;
  ggml_backend_load_all_from_path(arg0: bigint): Promise<void>;
  ggml_backend_meta_device(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_backend_meta_split_axis_name(arg0: number): Promise<bigint>;
  ggml_backend_name(arg0: bigint): Promise<bigint>;
  ggml_backend_offload_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_reg_by_name(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_count(): Promise<bigint>;
  ggml_backend_reg_dev_count(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_dev_get(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_reg_get(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_get_proc_address(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_reg_name(arg0: bigint): Promise<bigint>;
  ggml_backend_register(arg0: bigint): Promise<void>;
  ggml_backend_sched_alloc_graph(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_free(arg0: bigint): Promise<void>;
  ggml_backend_sched_get_backend(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_backend_sched_get_buffer_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_sched_get_buffer_type(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_sched_get_n_backends(arg0: bigint): Promise<number>;
  ggml_backend_sched_get_n_copies(arg0: bigint): Promise<number>;
  ggml_backend_sched_get_n_splits(arg0: bigint): Promise<number>;
  ggml_backend_sched_get_tensor_backend(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_sched_graph_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_graph_compute_async(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_new(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: number, arg5: number): Promise<bigint>;
  ggml_backend_sched_reserve(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_reserve_size(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_sched_reset(arg0: bigint): Promise<void>;
  ggml_backend_sched_set_eval_callback(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_sched_set_tensor_backend(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_sched_split_graph(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_sched_synchronize(arg0: bigint): Promise<void>;
  ggml_backend_supports_buft(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_supports_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_synchronize(arg0: bigint): Promise<void>;
  ggml_backend_tensor_alloc(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  ggml_backend_tensor_copy(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_tensor_copy_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_get(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_get_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  ggml_backend_tensor_get_2d_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void>;
  ggml_backend_tensor_get_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_backend_tensor_memset(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_set(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_set_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  ggml_backend_tensor_set_2d_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void>;
  ggml_backend_tensor_set_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_backend_unload(arg0: bigint): Promise<void>;
  ggml_backend_view_init(arg0: bigint): Promise<number>;
  ggml_bf16_to_fp32(arg0: bigint): Promise<number>;
  ggml_bf16_to_fp32_row(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_blck_size(arg0: number): Promise<bigint>;
  ggml_build_backward_expand(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_build_forward_expand(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_build_forward_order(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_build_forward_select(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_can_repeat(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_cast(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_ceil(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_ceil_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_clamp(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_clamp_inplace(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_col2im_1d(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number): Promise<bigint>;
  ggml_commit(): Promise<bigint>;
  ggml_concat(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_cont(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_cont_1d(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_cont_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_cont_3d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_cont_4d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_conv_1d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_conv_1d_dw(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_conv_1d_dw_ph(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_conv_1d_ph(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_conv_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint>;
  ggml_conv_2d_direct(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint>;
  ggml_conv_2d_dw(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint>;
  ggml_conv_2d_dw_direct(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint>;
  ggml_conv_2d_s1_ph(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_conv_2d_sk_p0(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_conv_3d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number): Promise<bigint>;
  ggml_conv_3d_direct(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number): Promise<bigint>;
  ggml_conv_transpose_1d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_conv_transpose_2d_p0(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_cos(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_cos_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_count_equal(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_cpu_bf16_to_fp32(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_cpu_fp16_to_fp32(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_cpu_fp32_to_bf16(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_cpu_fp32_to_fp16(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_cpu_fp32_to_fp32(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_cpu_fp32_to_i32(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_cpu_get_rvv_vlen(): Promise<number>;
  ggml_cpu_get_sve_cnt(): Promise<number>;
  ggml_cpu_has_amx_int8(): Promise<number>;
  ggml_cpu_has_arm_fma(): Promise<number>;
  ggml_cpu_has_avx(): Promise<number>;
  ggml_cpu_has_avx2(): Promise<number>;
  ggml_cpu_has_avx512(): Promise<number>;
  ggml_cpu_has_avx512_bf16(): Promise<number>;
  ggml_cpu_has_avx512_vbmi(): Promise<number>;
  ggml_cpu_has_avx512_vnni(): Promise<number>;
  ggml_cpu_has_avx_vnni(): Promise<number>;
  ggml_cpu_has_bmi2(): Promise<number>;
  ggml_cpu_has_dotprod(): Promise<number>;
  ggml_cpu_has_f16c(): Promise<number>;
  ggml_cpu_has_fma(): Promise<number>;
  ggml_cpu_has_fp16_va(): Promise<number>;
  ggml_cpu_has_llamafile(): Promise<number>;
  ggml_cpu_has_matmul_int8(): Promise<number>;
  ggml_cpu_has_neon(): Promise<number>;
  ggml_cpu_has_riscv_v(): Promise<number>;
  ggml_cpu_has_sme(): Promise<number>;
  ggml_cpu_has_sme2(): Promise<number>;
  ggml_cpu_has_sse3(): Promise<number>;
  ggml_cpu_has_ssse3(): Promise<number>;
  ggml_cpu_has_sve(): Promise<number>;
  ggml_cpu_has_vsx(): Promise<number>;
  ggml_cpu_has_vxe(): Promise<number>;
  ggml_cpu_has_wasm_simd(): Promise<number>;
  ggml_cpu_init(): Promise<void>;
  ggml_cpy(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_cross_entropy_loss(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_cross_entropy_loss_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_cumsum(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_custom_4d(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: number, arg8: bigint, arg9: number, arg10: bigint): Promise<bigint>;
  ggml_custom_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint, arg5: number, arg6: bigint): Promise<bigint>;
  ggml_cycles(): Promise<bigint>;
  ggml_cycles_per_ms(): Promise<bigint>;
  ggml_diag(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_diag_mask_inf(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_diag_mask_inf_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_diag_mask_zero(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_diag_mask_zero_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_div(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_div_inplace(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_dsv4_hc_comb(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number): Promise<bigint>;
  ggml_dsv4_hc_post(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_dsv4_hc_pre(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_dsv4_hc_pre_gated(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_dup(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_dup_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_dup_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_element_size(arg0: bigint): Promise<bigint>;
  ggml_elu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_elu_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_exp(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_exp_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_expm1(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_expm1_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_fill(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_fill_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_flash_attn_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number): Promise<bigint>;
  ggml_flash_attn_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number, arg6: number, arg7: number): Promise<bigint>;
  ggml_flash_attn_ext_add_sinks(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_flash_attn_ext_get_prec(arg0: bigint): Promise<number>;
  ggml_flash_attn_ext_set_n_kv_max(arg0: bigint, arg1: number): Promise<void>;
  ggml_floor(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_floor_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_fopen(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_fp16_to_fp32(arg0: number): Promise<number>;
  ggml_fp16_to_fp32_row(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_fp32_to_bf16(out: bigint, arg0: number): Promise<void>;
  ggml_fp32_to_bf16_row(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_fp32_to_bf16_row_ref(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_fp32_to_fp16(arg0: number): Promise<number>;
  ggml_fp32_to_fp16_row(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_free(arg0: bigint): Promise<void>;
  ggml_ftype_to_ggml_type(arg0: number): Promise<number>;
  ggml_gallocr_alloc_graph(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_gallocr_free(arg0: bigint): Promise<void>;
  ggml_gallocr_get_buffer_size(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_gallocr_new(arg0: bigint): Promise<bigint>;
  ggml_gallocr_new_n(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_gallocr_reserve(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_gallocr_reserve_n(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  ggml_gallocr_reserve_n_size(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_gated_delta_net(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<bigint>;
  ggml_gated_linear_attn(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: number): Promise<bigint>;
  ggml_geglu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_geglu_erf(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_geglu_erf_split(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_geglu_erf_swapped(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_geglu_quick(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_geglu_quick_split(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_geglu_quick_swapped(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_geglu_split(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_geglu_swapped(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_gelu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_gelu_erf(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_gelu_erf_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_gelu_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_gelu_quick(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_gelu_quick_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_get_data(arg0: bigint): Promise<bigint>;
  ggml_get_data_f32(arg0: bigint): Promise<bigint>;
  ggml_get_f32_1d(arg0: bigint, arg1: number): Promise<number>;
  ggml_get_f32_nd(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<number>;
  ggml_get_first_tensor(arg0: bigint): Promise<bigint>;
  ggml_get_glu_op(arg0: bigint): Promise<number>;
  ggml_get_i32_1d(arg0: bigint, arg1: number): Promise<number>;
  ggml_get_i32_nd(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<number>;
  ggml_get_max_tensor_size(arg0: bigint): Promise<bigint>;
  ggml_get_mem_buffer(arg0: bigint): Promise<bigint>;
  ggml_get_mem_size(arg0: bigint): Promise<bigint>;
  ggml_get_name(arg0: bigint): Promise<bigint>;
  ggml_get_next_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_get_no_alloc(arg0: bigint): Promise<number>;
  ggml_get_rel_pos(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_get_rows(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_get_rows_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_get_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_get_type_traits(arg0: number): Promise<bigint>;
  ggml_get_type_traits_cpu(arg0: number): Promise<bigint>;
  ggml_get_unary_op(arg0: bigint): Promise<number>;
  ggml_glu(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_glu_op_name(arg0: number): Promise<bigint>;
  ggml_glu_split(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_graph_add_node(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_graph_clear(arg0: bigint): Promise<void>;
  ggml_graph_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_graph_compute_with_ctx(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  ggml_graph_cpy(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_graph_dump_dot(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_graph_dup(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_graph_get_grad(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_graph_get_grad_acc(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_graph_get_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_graph_n_nodes(arg0: bigint): Promise<number>;
  ggml_graph_node(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_graph_nodes(arg0: bigint): Promise<bigint>;
  ggml_graph_overhead(): Promise<bigint>;
  ggml_graph_overhead_custom(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_graph_plan(out: bigint, arg0: bigint, arg1: number, arg2: bigint): Promise<void>;
  ggml_graph_print(arg0: bigint): Promise<void>;
  ggml_graph_reset(arg0: bigint): Promise<void>;
  ggml_graph_size(arg0: bigint): Promise<number>;
  ggml_group_norm(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_group_norm_inplace(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_guid_matches(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_hardsigmoid(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_hardswish(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_im2col(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): Promise<bigint>;
  ggml_im2col_3d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number): Promise<bigint>;
  ggml_im2col_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): Promise<bigint>;
  ggml_init(arg0: bigint): Promise<bigint>;
  ggml_interpolate(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: number): Promise<bigint>;
  ggml_is_3d(arg0: bigint): Promise<number>;
  ggml_is_contiguous(arg0: bigint): Promise<number>;
  ggml_is_contiguous_0(arg0: bigint): Promise<number>;
  ggml_is_contiguous_1(arg0: bigint): Promise<number>;
  ggml_is_contiguous_2(arg0: bigint): Promise<number>;
  ggml_is_contiguous_channels(arg0: bigint): Promise<number>;
  ggml_is_contiguous_rows(arg0: bigint): Promise<number>;
  ggml_is_contiguous_to_1(arg0: bigint): Promise<number>;
  ggml_is_contiguous_to_2(arg0: bigint): Promise<number>;
  ggml_is_contiguous_to_3(arg0: bigint): Promise<number>;
  ggml_is_contiguously_allocated(arg0: bigint): Promise<number>;
  ggml_is_empty(arg0: bigint): Promise<number>;
  ggml_is_matrix(arg0: bigint): Promise<number>;
  ggml_is_numa(): Promise<number>;
  ggml_is_permuted(arg0: bigint): Promise<number>;
  ggml_is_quantized(arg0: number): Promise<number>;
  ggml_is_scalar(arg0: bigint): Promise<number>;
  ggml_is_transposed(arg0: bigint): Promise<number>;
  ggml_is_vector(arg0: bigint): Promise<number>;
  ggml_is_view(arg0: bigint): Promise<number>;
  ggml_l2_norm(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_l2_norm_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_leaky_relu(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_lightning_indexer(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_log(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_log_get(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_log_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_map_custom1(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint): Promise<bigint>;
  ggml_map_custom1_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint): Promise<bigint>;
  ggml_map_custom2(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: bigint): Promise<bigint>;
  ggml_map_custom2_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: bigint): Promise<bigint>;
  ggml_map_custom3(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number, arg6: bigint): Promise<bigint>;
  ggml_map_custom3_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number, arg6: bigint): Promise<bigint>;
  ggml_mean(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_mul(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_mul_inplace(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_mul_mat(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_mul_mat_id(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_mul_mat_set_hint(arg0: bigint, arg1: number): Promise<void>;
  ggml_n_dims(arg0: bigint): Promise<number>;
  ggml_nbytes(arg0: bigint): Promise<bigint>;
  ggml_nbytes_pad(arg0: bigint): Promise<bigint>;
  ggml_neg(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_neg_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_nelements(arg0: bigint): Promise<bigint>;
  ggml_new_buffer(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_new_f32(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_new_graph(arg0: bigint): Promise<bigint>;
  ggml_new_graph_custom(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_new_i32(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_new_tensor(arg0: bigint, arg1: number, arg2: number, arg3: bigint): Promise<bigint>;
  ggml_new_tensor_1d(arg0: bigint, arg1: number, arg2: bigint): Promise<bigint>;
  ggml_new_tensor_2d(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_new_tensor_3d(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_new_tensor_4d(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_norm(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_norm_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_nrows(arg0: bigint): Promise<bigint>;
  ggml_numa_init(arg0: number): Promise<void>;
  ggml_op_desc(arg0: bigint): Promise<bigint>;
  ggml_op_name(arg0: number): Promise<bigint>;
  ggml_op_symbol(arg0: number): Promise<bigint>;
  ggml_opt_alloc(arg0: bigint, arg1: number): Promise<void>;
  ggml_opt_context_optimizer_type(arg0: bigint): Promise<number>;
  ggml_opt_dataset_data(arg0: bigint): Promise<bigint>;
  ggml_opt_dataset_free(arg0: bigint): Promise<void>;
  ggml_opt_dataset_get_batch(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_opt_dataset_get_batch_host(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_opt_dataset_init(arg0: number, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_opt_dataset_labels(arg0: bigint): Promise<bigint>;
  ggml_opt_dataset_ndata(arg0: bigint): Promise<bigint>;
  ggml_opt_dataset_shuffle(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_opt_default_params(out: bigint, arg0: bigint, arg1: number): Promise<void>;
  ggml_opt_epoch(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  ggml_opt_epoch_callback_progress_bar(arg0: number, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  ggml_opt_eval(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_opt_fit(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number, arg6: number, arg7: bigint, arg8: bigint, arg9: bigint, arg10: number, arg11: number): Promise<void>;
  ggml_opt_free(arg0: bigint): Promise<void>;
  ggml_opt_get_constant_optimizer_params(out: bigint, arg0: bigint): Promise<void>;
  ggml_opt_get_default_optimizer_params(out: bigint, arg0: bigint): Promise<void>;
  ggml_opt_grad_acc(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_opt_init(arg0: bigint): Promise<bigint>;
  ggml_opt_inputs(arg0: bigint): Promise<bigint>;
  ggml_opt_labels(arg0: bigint): Promise<bigint>;
  ggml_opt_loss(arg0: bigint): Promise<bigint>;
  ggml_opt_ncorrect(arg0: bigint): Promise<bigint>;
  ggml_opt_optimizer_name(arg0: number): Promise<bigint>;
  ggml_opt_outputs(arg0: bigint): Promise<bigint>;
  ggml_opt_pred(arg0: bigint): Promise<bigint>;
  ggml_opt_prepare_alloc(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_opt_reset(arg0: bigint, arg1: number): Promise<void>;
  ggml_opt_result_accuracy(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_opt_result_free(arg0: bigint): Promise<void>;
  ggml_opt_result_init(): Promise<bigint>;
  ggml_opt_result_loss(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_opt_result_ndata(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_opt_result_pred(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_opt_result_reset(arg0: bigint): Promise<void>;
  ggml_opt_static_graphs(arg0: bigint): Promise<number>;
  ggml_opt_step_adamw(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_opt_step_sgd(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_out_prod(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_pad(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_pad_circular(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_pad_ext(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): Promise<bigint>;
  ggml_pad_ext_circular(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): Promise<bigint>;
  ggml_pad_reflect_1d(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_permute(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_pool_1d(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_pool_2d(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): Promise<bigint>;
  ggml_pool_2d_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number): Promise<bigint>;
  ggml_prec_set_acc(arg0: bigint, arg1: number): Promise<number>;
  ggml_prec_set_src(arg0: bigint, arg1: number, arg2: number): Promise<number>;
  ggml_print_object(arg0: bigint): Promise<void>;
  ggml_print_objects(arg0: bigint): Promise<void>;
  ggml_quantize_chunk(arg0: number, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  ggml_quantize_free(): Promise<void>;
  ggml_quantize_init(arg0: number): Promise<void>;
  ggml_quantize_requires_imatrix(arg0: number): Promise<number>;
  ggml_reglu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_reglu_split(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_reglu_swapped(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_relu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_relu_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_repeat(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_repeat_4d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_repeat_back(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_reset(arg0: bigint): Promise<void>;
  ggml_reshape(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_reshape_1d(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_reshape_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_reshape_3d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_reshape_4d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_rms_norm(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_rms_norm_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_rms_norm_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_roll(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_rope(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_rope_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number): Promise<bigint>;
  ggml_rope_ext_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number): Promise<bigint>;
  ggml_rope_ext_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number): Promise<bigint>;
  ggml_rope_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_rope_multi(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: bigint, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number): Promise<bigint>;
  ggml_rope_multi_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: bigint, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number): Promise<bigint>;
  ggml_rope_multi_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: bigint, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number): Promise<bigint>;
  ggml_rope_set_offset(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_rope_yarn_corr_dims(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: bigint): Promise<void>;
  ggml_round(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_round_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_row_size(arg0: number, arg1: bigint): Promise<bigint>;
  ggml_rwkv_wkv6(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  ggml_rwkv_wkv7(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<bigint>;
  ggml_scale(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_scale_bias(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_scale_bias_inplace(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_scale_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_set(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  ggml_set_1d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_set_1d_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_set_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_set_2d_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  ggml_set_abort_callback(arg0: bigint): Promise<bigint>;
  ggml_set_f32(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_set_f32_1d(arg0: bigint, arg1: number, arg2: number): Promise<void>;
  ggml_set_f32_nd(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Promise<void>;
  ggml_set_i32(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_set_i32_1d(arg0: bigint, arg1: number, arg2: number): Promise<void>;
  ggml_set_i32_nd(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Promise<void>;
  ggml_set_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  ggml_set_input(arg0: bigint): Promise<void>;
  ggml_set_loss(arg0: bigint): Promise<void>;
  ggml_set_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_set_no_alloc(arg0: bigint, arg1: number): Promise<void>;
  ggml_set_output(arg0: bigint): Promise<void>;
  ggml_set_param(arg0: bigint): Promise<void>;
  ggml_set_rows(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_set_zero(arg0: bigint): Promise<bigint>;
  ggml_sgn(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sgn_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sigmoid(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sigmoid_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_silu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_silu_back(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_silu_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sin(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sin_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_soft_max(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_soft_max_add_sinks(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_soft_max_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_soft_max_ext_back(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_soft_max_ext_back_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_soft_max_ext_inplace(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_soft_max_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_softplus(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_softplus_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_solve_tri(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  ggml_sqr(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sqr_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sqrt(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sqrt_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_ssm_conv(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_ssm_scan(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint): Promise<bigint>;
  ggml_status_to_string(arg0: number): Promise<bigint>;
  ggml_step(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_step_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sub(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_sub_inplace(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_sum(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_sum_rows(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_swiglu(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_swiglu_clamp(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  ggml_swiglu_oai(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  ggml_swiglu_split(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  ggml_swiglu_swapped(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_tallocr_alloc(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_tallocr_new(out: bigint, arg0: bigint): Promise<void>;
  ggml_tanh(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_tanh_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_tensor_overhead(): Promise<bigint>;
  ggml_threadpool_free(arg0: bigint): Promise<void>;
  ggml_threadpool_new(arg0: bigint): Promise<bigint>;
  ggml_threadpool_params_default(out: bigint, arg0: number): Promise<void>;
  ggml_threadpool_params_init(arg0: bigint, arg1: number): Promise<void>;
  ggml_threadpool_params_match(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_threadpool_pause(arg0: bigint): Promise<void>;
  ggml_threadpool_resume(arg0: bigint): Promise<void>;
  ggml_time_init(): Promise<void>;
  ggml_time_ms(): Promise<bigint>;
  ggml_time_us(): Promise<bigint>;
  ggml_timestep_embedding(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_top_k(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_transpose(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_tri(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_trunc(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_trunc_inplace(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_type_name(arg0: number): Promise<bigint>;
  ggml_type_size(arg0: number): Promise<bigint>;
  ggml_unary(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_unary_inplace(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_unary_op_name(arg0: number): Promise<bigint>;
  ggml_unravel_index(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void>;
  ggml_upscale(arg0: bigint, arg1: bigint, arg2: number, arg3: number): Promise<bigint>;
  ggml_used_mem(arg0: bigint): Promise<bigint>;
  ggml_validate_row_data(arg0: number, arg1: bigint, arg2: bigint): Promise<number>;
  ggml_version(): Promise<bigint>;
  ggml_view_1d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_view_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  ggml_view_3d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<bigint>;
  ggml_view_4d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint): Promise<bigint>;
  ggml_view_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_win_part(arg0: bigint, arg1: bigint, arg2: number): Promise<bigint>;
  ggml_win_unpart(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number): Promise<bigint>;
  ggml_xielu(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: number): Promise<bigint>;
  gguf_add_tensor(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_find_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_find_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_free(arg0: bigint): Promise<void>;
  gguf_get_alignment(arg0: bigint): Promise<bigint>;
  gguf_get_arr_data(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_arr_n(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_arr_str(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  gguf_get_arr_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_data_offset(arg0: bigint): Promise<bigint>;
  gguf_get_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_kv_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_meta_data(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_get_meta_size(arg0: bigint): Promise<bigint>;
  gguf_get_n_kv(arg0: bigint): Promise<bigint>;
  gguf_get_n_tensors(arg0: bigint): Promise<bigint>;
  gguf_get_tensor_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_ne(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_offset(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_bool(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_data(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_f32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_f64(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i16(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i64(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_i8(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_str(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_u16(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_u32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_u64(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_u8(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_version(arg0: bigint): Promise<number>;
  gguf_init_empty(): Promise<bigint>;
  gguf_init_from_buffer(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  gguf_init_from_callback(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  gguf_init_from_file(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_init_from_file_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_remove_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_set_arr_data(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint): Promise<void>;
  gguf_set_arr_str(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  gguf_set_kv(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_set_tensor_data(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_tensor_type(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_bool(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_f32(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_f64(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_i16(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_i32(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_i64(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_val_i8(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_str(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_val_u16(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_u32(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_u64(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_val_u8(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_type_name(arg0: number): Promise<bigint>;
  gguf_write_to_file(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  gguf_write_to_file_ptr(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  llama_adapter_get_alora_invocation_tokens(arg0: bigint): Promise<bigint>;
  llama_adapter_get_alora_n_invocation_tokens(arg0: bigint): Promise<bigint>;
  llama_adapter_lora_free(arg0: bigint): Promise<void>;
  llama_adapter_lora_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_adapter_lora_init_from_file_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_adapter_meta_count(arg0: bigint): Promise<number>;
  llama_adapter_meta_key_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_adapter_meta_val_str(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_adapter_meta_val_str_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_attach_threadpool(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  llama_backend_free(): Promise<void>;
  llama_backend_init(): Promise<void>;
  llama_batch_ext_add(arg0: bigint, arg1: number): Promise<number>;
  llama_batch_ext_add_embd(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_batch_ext_add_seq(arg0: bigint, arg1: number, arg2: number): Promise<number>;
  llama_batch_ext_add_token(arg0: bigint, arg1: number, arg2: number): Promise<number>;
  llama_batch_ext_clear(arg0: bigint): Promise<void>;
  llama_batch_ext_free(arg0: bigint): Promise<void>;
  llama_batch_ext_init(arg0: bigint): Promise<bigint>;
  llama_batch_ext_set_embd_state(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_batch_ext_set_embd_token(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_batch_ext_set_output_embd(arg0: bigint, arg1: number, arg2: number): Promise<number>;
  llama_batch_ext_set_output_logits(arg0: bigint, arg1: number, arg2: number): Promise<number>;
  llama_batch_ext_set_pos(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_batch_free(arg0: bigint): Promise<void>;
  llama_batch_get_one(out: bigint, arg0: bigint, arg1: number): Promise<void>;
  llama_batch_init(out: bigint, arg0: number, arg1: number, arg2: number): Promise<void>;
  llama_chat_apply_template(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint, arg5: number): Promise<number>;
  llama_chat_builtin_templates(arg0: bigint, arg1: bigint): Promise<number>;
  llama_context_default_params(out: bigint): Promise<void>;
  llama_decode(arg0: bigint, arg1: bigint): Promise<number>;
  llama_detach_threadpool(arg0: bigint): Promise<void>;
  llama_detokenize(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: number, arg5: number, arg6: number): Promise<number>;
  llama_encode(arg0: bigint, arg1: bigint): Promise<number>;
  llama_flash_attn_type_name(arg0: number): Promise<bigint>;
  llama_free(arg0: bigint): Promise<void>;
  llama_ftype_name(arg0: number): Promise<bigint>;
  llama_get_causal_attn(arg0: bigint): Promise<number>;
  llama_get_embeddings(arg0: bigint): Promise<bigint>;
  llama_get_embeddings_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_embeddings_seq(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_logits(arg0: bigint): Promise<bigint>;
  llama_get_logits_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_memory(arg0: bigint): Promise<bigint>;
  llama_get_model(arg0: bigint): Promise<bigint>;
  llama_get_sampled_candidates_count_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_get_sampled_candidates_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_sampled_logits_count_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_get_sampled_logits_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_sampled_probs_count_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_get_sampled_probs_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_sampled_token_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_init_from_model(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_load_mode_from_str(arg0: bigint): Promise<number>;
  llama_load_mode_name(arg0: number): Promise<bigint>;
  llama_log_get(arg0: bigint, arg1: bigint): Promise<void>;
  llama_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  llama_max_devices(): Promise<bigint>;
  llama_max_parallel_sequences(): Promise<bigint>;
  llama_max_tensor_buft_overrides(): Promise<bigint>;
  llama_memory_can_shift(arg0: bigint): Promise<number>;
  llama_memory_clear(arg0: bigint, arg1: number): Promise<void>;
  llama_memory_seq_add(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void>;
  llama_memory_seq_cp(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void>;
  llama_memory_seq_div(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void>;
  llama_memory_seq_keep(arg0: bigint, arg1: number): Promise<void>;
  llama_memory_seq_pos_max(arg0: bigint, arg1: number): Promise<number>;
  llama_memory_seq_pos_min(arg0: bigint, arg1: number): Promise<number>;
  llama_memory_seq_rm(arg0: bigint, arg1: number, arg2: number, arg3: number): Promise<number>;
  llama_model_chat_template(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_model_cls_label(arg0: bigint, arg1: number): Promise<bigint>;
  llama_model_decoder_start_token(arg0: bigint): Promise<number>;
  llama_model_default_params(out: bigint): Promise<void>;
  llama_model_desc(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  llama_model_free(arg0: bigint): Promise<void>;
  llama_model_ftype(arg0: bigint): Promise<number>;
  llama_model_get_vocab(arg0: bigint): Promise<bigint>;
  llama_model_has_decoder(arg0: bigint): Promise<number>;
  llama_model_has_encoder(arg0: bigint): Promise<number>;
  llama_model_init_from_user(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  llama_model_is_diffusion(arg0: bigint): Promise<number>;
  llama_model_is_hybrid(arg0: bigint): Promise<number>;
  llama_model_is_recurrent(arg0: bigint): Promise<number>;
  llama_model_load_from_file(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_model_load_from_file_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_model_load_from_splits(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_model_meta_count(arg0: bigint): Promise<number>;
  llama_model_meta_key_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_model_meta_key_str(arg0: number): Promise<bigint>;
  llama_model_meta_val_str(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_model_meta_val_str_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_model_n_cls_out(arg0: bigint): Promise<number>;
  llama_model_n_ctx_train(arg0: bigint): Promise<number>;
  llama_model_n_embd(arg0: bigint): Promise<number>;
  llama_model_n_embd_inp(arg0: bigint): Promise<number>;
  llama_model_n_embd_out(arg0: bigint): Promise<number>;
  llama_model_n_head(arg0: bigint): Promise<number>;
  llama_model_n_head_kv(arg0: bigint): Promise<number>;
  llama_model_n_layer(arg0: bigint): Promise<number>;
  llama_model_n_layer_nextn(arg0: bigint): Promise<number>;
  llama_model_n_params(arg0: bigint): Promise<bigint>;
  llama_model_n_swa(arg0: bigint): Promise<number>;
  llama_model_quantize(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  llama_model_quantize_default_params(out: bigint): Promise<void>;
  llama_model_rope_freq_scale_train(arg0: bigint): Promise<number>;
  llama_model_rope_type(arg0: bigint): Promise<number>;
  llama_model_save_to_file(arg0: bigint, arg1: bigint): Promise<void>;
  llama_model_size(arg0: bigint): Promise<bigint>;
  llama_n_batch(arg0: bigint): Promise<number>;
  llama_n_ctx(arg0: bigint): Promise<number>;
  llama_n_ctx_seq(arg0: bigint): Promise<number>;
  llama_n_rs_seq(arg0: bigint): Promise<number>;
  llama_n_seq_max(arg0: bigint): Promise<number>;
  llama_n_threads(arg0: bigint): Promise<number>;
  llama_n_threads_batch(arg0: bigint): Promise<number>;
  llama_n_ubatch(arg0: bigint): Promise<number>;
  llama_numa_init(arg0: number): Promise<void>;
  llama_opt_epoch(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  llama_opt_init(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  llama_opt_param_filter_all(arg0: bigint, arg1: bigint): Promise<number>;
  llama_perf_context(out: bigint, arg0: bigint): Promise<void>;
  llama_perf_context_print(arg0: bigint): Promise<void>;
  llama_perf_context_reset(arg0: bigint): Promise<void>;
  llama_perf_sampler(out: bigint, arg0: bigint): Promise<void>;
  llama_perf_sampler_print(arg0: bigint): Promise<void>;
  llama_perf_sampler_reset(arg0: bigint): Promise<void>;
  llama_pooling_type(arg0: bigint): Promise<number>;
  llama_print_system_info(): Promise<bigint>;
  llama_process(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_sampler_accept(arg0: bigint, arg1: number): Promise<void>;
  llama_sampler_apply(arg0: bigint, arg1: bigint): Promise<void>;
  llama_sampler_chain_add(arg0: bigint, arg1: bigint): Promise<void>;
  llama_sampler_chain_default_params(out: bigint): Promise<void>;
  llama_sampler_chain_get(arg0: bigint, arg1: number): Promise<bigint>;
  llama_sampler_chain_init(arg0: bigint): Promise<bigint>;
  llama_sampler_chain_n(arg0: bigint): Promise<number>;
  llama_sampler_chain_remove(arg0: bigint, arg1: number): Promise<bigint>;
  llama_sampler_clone(arg0: bigint): Promise<bigint>;
  llama_sampler_copy(arg0: bigint, arg1: bigint): Promise<void>;
  llama_sampler_free(arg0: bigint): Promise<void>;
  llama_sampler_get_seed(arg0: bigint): Promise<number>;
  llama_sampler_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_sampler_init_adaptive_p(arg0: number, arg1: number, arg2: number): Promise<bigint>;
  llama_sampler_init_dist(arg0: number): Promise<bigint>;
  llama_sampler_init_dry(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: bigint, arg6: bigint): Promise<bigint>;
  llama_sampler_init_grammar(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_sampler_init_grammar_lazy_patterns(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  llama_sampler_init_greedy(): Promise<bigint>;
  llama_sampler_init_infill(arg0: bigint): Promise<bigint>;
  llama_sampler_init_logit_bias(arg0: number, arg1: number, arg2: bigint): Promise<bigint>;
  llama_sampler_init_min_p(arg0: number, arg1: bigint): Promise<bigint>;
  llama_sampler_init_mirostat(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): Promise<bigint>;
  llama_sampler_init_mirostat_v2(arg0: number, arg1: number, arg2: number): Promise<bigint>;
  llama_sampler_init_penalties(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): Promise<bigint>;
  llama_sampler_init_temp(arg0: number): Promise<bigint>;
  llama_sampler_init_temp_ext(arg0: number, arg1: number, arg2: number): Promise<bigint>;
  llama_sampler_init_top_k(arg0: number): Promise<bigint>;
  llama_sampler_init_top_n_sigma(arg0: number): Promise<bigint>;
  llama_sampler_init_top_p(arg0: number, arg1: bigint): Promise<bigint>;
  llama_sampler_init_typical(arg0: number, arg1: bigint): Promise<bigint>;
  llama_sampler_init_xtc(arg0: number, arg1: number, arg2: bigint, arg3: number): Promise<bigint>;
  llama_sampler_name(arg0: bigint): Promise<bigint>;
  llama_sampler_reset(arg0: bigint): Promise<void>;
  llama_sampler_sample(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  llama_set_abort_callback(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  llama_set_adapter_cvec(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<number>;
  llama_set_adapters_lora(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_set_causal_attn(arg0: bigint, arg1: number): Promise<void>;
  llama_set_embeddings(arg0: bigint, arg1: number): Promise<void>;
  llama_set_n_threads(arg0: bigint, arg1: number, arg2: number): Promise<void>;
  llama_set_sampler(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_split_path(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<number>;
  llama_split_prefix(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<number>;
  llama_state_get_data(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_state_get_size(arg0: bigint): Promise<bigint>;
  llama_state_load_file(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  llama_state_save_file(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_state_seq_get_data(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  llama_state_seq_get_data_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  llama_state_seq_get_size(arg0: bigint, arg1: number): Promise<bigint>;
  llama_state_seq_get_size_ext(arg0: bigint, arg1: number, arg2: number): Promise<bigint>;
  llama_state_seq_load_file(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  llama_state_seq_save_file(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint): Promise<bigint>;
  llama_state_seq_set_data(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  llama_state_seq_set_data_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  llama_state_set_data(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_supports_gpu_offload(): Promise<number>;
  llama_supports_mlock(): Promise<number>;
  llama_supports_mmap(): Promise<number>;
  llama_supports_rpc(): Promise<number>;
  llama_synchronize(arg0: bigint): Promise<void>;
  llama_time_us(): Promise<bigint>;
  llama_token_to_piece(arg0: bigint, arg1: number, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<number>;
  llama_tokenize(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: number, arg5: number, arg6: number): Promise<number>;
  llama_version(): Promise<bigint>;
  llama_vocab_bos(arg0: bigint): Promise<number>;
  llama_vocab_eos(arg0: bigint): Promise<number>;
  llama_vocab_eot(arg0: bigint): Promise<number>;
  llama_vocab_fim_mid(arg0: bigint): Promise<number>;
  llama_vocab_fim_pad(arg0: bigint): Promise<number>;
  llama_vocab_fim_pre(arg0: bigint): Promise<number>;
  llama_vocab_fim_rep(arg0: bigint): Promise<number>;
  llama_vocab_fim_sep(arg0: bigint): Promise<number>;
  llama_vocab_fim_suf(arg0: bigint): Promise<number>;
  llama_vocab_get_add_bos(arg0: bigint): Promise<number>;
  llama_vocab_get_add_eos(arg0: bigint): Promise<number>;
  llama_vocab_get_add_sep(arg0: bigint): Promise<number>;
  llama_vocab_get_attr(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_get_score(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_get_suppress_tokens(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_vocab_get_text(arg0: bigint, arg1: number): Promise<bigint>;
  llama_vocab_is_control(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_is_eog(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_mask(arg0: bigint): Promise<number>;
  llama_vocab_n_tokens(arg0: bigint): Promise<number>;
  llama_vocab_nl(arg0: bigint): Promise<number>;
  llama_vocab_pad(arg0: bigint): Promise<number>;
  llama_vocab_sep(arg0: bigint): Promise<number>;
  llama_vocab_type(arg0: bigint): Promise<number>;
  mtmd_batch_add_chunk(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_batch_encode(arg0: bigint): Promise<number>;
  mtmd_batch_free(arg0: bigint): Promise<void>;
  mtmd_batch_get_output_embd(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_batch_init(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_free(arg0: bigint): Promise<void>;
  mtmd_bitmap_get_data(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_get_id(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_get_n_bytes(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_get_nx(arg0: bigint): Promise<number>;
  mtmd_bitmap_get_ny(arg0: bigint): Promise<number>;
  mtmd_bitmap_init(arg0: number, arg1: number, arg2: bigint): Promise<bigint>;
  mtmd_bitmap_init_from_audio(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_bitmap_init_lazy(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  mtmd_bitmap_is_audio(arg0: bigint): Promise<number>;
  mtmd_bitmap_set_id(arg0: bigint, arg1: bigint): Promise<void>;
  mtmd_bitmap_set_mergeable(arg0: bigint, arg1: number): Promise<void>;
  mtmd_context_params_default(out: bigint): Promise<void>;
  mtmd_decode_use_mrope(arg0: bigint): Promise<number>;
  mtmd_decode_use_non_causal(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_default_marker(): Promise<bigint>;
  mtmd_encode_chunk(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_free(arg0: bigint): Promise<void>;
  mtmd_gen_audio_get_info(out: bigint, arg0: bigint): Promise<void>;
  mtmd_gen_audio_process(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  mtmd_gen_inp_default(out: bigint, arg0: bigint): Promise<void>;
  mtmd_get_audio_sample_rate(arg0: bigint): Promise<number>;
  mtmd_get_cap_from_file(out: bigint, arg0: bigint): Promise<void>;
  mtmd_get_marker(arg0: bigint): Promise<bigint>;
  mtmd_get_output_embd(arg0: bigint): Promise<bigint>;
  mtmd_helper_bitmap_init_from_buf(out: bigint, arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint): Promise<void>;
  mtmd_helper_bitmap_init_from_file(out: bigint, arg0: bigint, arg1: bigint, arg2: number, arg3: bigint): Promise<void>;
  mtmd_helper_decode_image_chunk(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: bigint, arg8: bigint, arg9: bigint): Promise<number>;
  mtmd_helper_eval_chunk_single(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: bigint): Promise<number>;
  mtmd_helper_eval_chunks(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: bigint): Promise<number>;
  mtmd_helper_gen_audio_free(arg0: bigint): Promise<void>;
  mtmd_helper_gen_audio_get_output(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  mtmd_helper_gen_audio_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_helper_gen_audio_reset(arg0: bigint): Promise<void>;
  mtmd_helper_gen_audio_set_input(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_helper_gen_audio_step_gen(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  mtmd_helper_gen_audio_step_prompt(arg0: bigint, arg1: number): Promise<number>;
  mtmd_helper_get_n_pos(arg0: bigint): Promise<number>;
  mtmd_helper_get_n_tokens(arg0: bigint): Promise<bigint>;
  mtmd_helper_image_get_decoder_pos(arg0: bigint, arg1: number, arg2: bigint): Promise<void>;
  mtmd_helper_init_opt_default(out: bigint): Promise<void>;
  mtmd_helper_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  mtmd_helper_model_can_chat(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_helper_support_video(arg0: bigint): Promise<number>;
  mtmd_helper_video_init_params_default(out: bigint): Promise<void>;
  mtmd_image_tokens_get_decoder_pos(out: bigint, arg0: bigint, arg1: number, arg2: bigint): Promise<void>;
  mtmd_image_tokens_get_id(arg0: bigint): Promise<bigint>;
  mtmd_image_tokens_get_n_pos(arg0: bigint): Promise<number>;
  mtmd_image_tokens_get_n_tokens(arg0: bigint): Promise<bigint>;
  mtmd_init_from_file(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  mtmd_input_chunk_copy(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_free(arg0: bigint): Promise<void>;
  mtmd_input_chunk_get_id(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_n_pos(arg0: bigint): Promise<number>;
  mtmd_input_chunk_get_n_tokens(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_placeholder(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_tokens_image(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_tokens_text(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_input_chunk_get_type(arg0: bigint): Promise<number>;
  mtmd_input_chunk_load(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_input_chunk_save(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  mtmd_input_chunks_free(arg0: bigint): Promise<void>;
  mtmd_input_chunks_get(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_input_chunks_init(): Promise<bigint>;
  mtmd_input_chunks_size(arg0: bigint): Promise<bigint>;
  mtmd_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  mtmd_support_audio(arg0: bigint): Promise<number>;
  mtmd_support_vision(arg0: bigint): Promise<number>;
  mtmd_test_create_input_chunks(): Promise<bigint>;
  mtmd_tokenize(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  mtmd_tokenize_from_parts(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number): Promise<number>;
}
