/** Generated from the pinned headers. Pointer and size arguments use bigint. */
export interface LowLevelFunctions {
  adetail_image(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<number>;
  convert(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint, arg5: number): Promise<number>;
  convert_with_components(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: number, arg8: bigint, arg9: number, arg10: number): Promise<number>;
  disable_imatrix_collection(): Promise<void>;
  enable_imatrix_collection(): Promise<void>;
  free_adetailer_ctx(arg0: bigint): Promise<void>;
  free_sd_audio(arg0: bigint): Promise<void>;
  free_sd_ctx(arg0: bigint): Promise<void>;
  free_sd_images(arg0: bigint, arg1: number): Promise<void>;
  free_upscaler_ctx(arg0: bigint): Promise<void>;
  generate_image(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  generate_video(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<number>;
  get_upscale_factor(arg0: bigint): Promise<number>;
  ggml_are_same_shape(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_are_same_stride(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_alloc_buffer(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buffer_free(arg0: bigint): Promise<void>;
  ggml_backend_buffer_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_alloc_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buffer_get_base(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_type(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_usage(arg0: bigint): Promise<number>;
  ggml_backend_buffer_is_host(arg0: bigint): Promise<number>;
  ggml_backend_buffer_name(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_alloc_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buft_get_device(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_is_host(arg0: bigint): Promise<number>;
  ggml_backend_buft_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_backend_reg(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_by_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_by_type(arg0: number): Promise<bigint>;
  ggml_backend_dev_count(): Promise<bigint>;
  ggml_backend_dev_description(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_get(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_get_props(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_dev_host_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_dev_memory(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_dev_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_offload_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_supports_buft(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_supports_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_type(arg0: bigint): Promise<number>;
  ggml_backend_free(arg0: bigint): Promise<void>;
  ggml_backend_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_get_default_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_get_device(arg0: bigint): Promise<bigint>;
  ggml_backend_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_init_best(): Promise<bigint>;
  ggml_backend_init_by_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_init_by_type(arg0: number, arg1: bigint): Promise<bigint>;
  ggml_backend_load_all(): Promise<void>;
  ggml_backend_name(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_by_name(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_count(): Promise<bigint>;
  ggml_backend_reg_dev_count(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_dev_get(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_reg_get(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_name(arg0: bigint): Promise<bigint>;
  ggml_bf16_to_fp32(arg0: bigint): Promise<number>;
  ggml_blck_size(arg0: number): Promise<bigint>;
  ggml_commit(): Promise<bigint>;
  ggml_cpu_get_rvv_vlen(): Promise<number>;
  ggml_cpu_get_sve_cnt(): Promise<number>;
  ggml_cpu_has_amx_int8(): Promise<number>;
  ggml_cpu_has_arm_fma(): Promise<number>;
  ggml_cpu_has_avx(): Promise<number>;
  ggml_cpu_has_avx2(): Promise<number>;
  ggml_cpu_has_avx512(): Promise<number>;
  ggml_cpu_has_avx512_bf16(): Promise<number>;
  ggml_cpu_has_avx512_vbmi(): Promise<number>;
  ggml_cpu_has_avx512_vnni(): Promise<number>;
  ggml_cpu_has_avx_vnni(): Promise<number>;
  ggml_cpu_has_bmi2(): Promise<number>;
  ggml_cpu_has_dotprod(): Promise<number>;
  ggml_cpu_has_f16c(): Promise<number>;
  ggml_cpu_has_fma(): Promise<number>;
  ggml_cpu_has_fp16_va(): Promise<number>;
  ggml_cpu_has_llamafile(): Promise<number>;
  ggml_cpu_has_matmul_int8(): Promise<number>;
  ggml_cpu_has_neon(): Promise<number>;
  ggml_cpu_has_riscv_v(): Promise<number>;
  ggml_cpu_has_sme(): Promise<number>;
  ggml_cpu_has_sme2(): Promise<number>;
  ggml_cpu_has_sse3(): Promise<number>;
  ggml_cpu_has_ssse3(): Promise<number>;
  ggml_cpu_has_sve(): Promise<number>;
  ggml_cpu_has_vsx(): Promise<number>;
  ggml_cpu_has_vxe(): Promise<number>;
  ggml_cpu_has_wasm_simd(): Promise<number>;
  ggml_element_size(arg0: bigint): Promise<bigint>;
  ggml_fp16_to_fp32(arg0: number): Promise<number>;
  ggml_fp32_to_bf16(out: bigint, arg0: number): Promise<void>;
  ggml_fp32_to_fp16(arg0: number): Promise<number>;
  ggml_ftype_to_ggml_type(arg0: number): Promise<number>;
  ggml_get_data(arg0: bigint): Promise<bigint>;
  ggml_get_data_f32(arg0: bigint): Promise<bigint>;
  ggml_get_name(arg0: bigint): Promise<bigint>;
  ggml_get_type_traits(arg0: number): Promise<bigint>;
  ggml_glu_op_name(arg0: number): Promise<bigint>;
  ggml_is_3d(arg0: bigint): Promise<number>;
  ggml_is_contiguous(arg0: bigint): Promise<number>;
  ggml_is_contiguous_0(arg0: bigint): Promise<number>;
  ggml_is_contiguous_1(arg0: bigint): Promise<number>;
  ggml_is_contiguous_2(arg0: bigint): Promise<number>;
  ggml_is_contiguous_to_1(arg0: bigint): Promise<number>;
  ggml_is_contiguous_to_2(arg0: bigint): Promise<number>;
  ggml_is_contiguous_to_3(arg0: bigint): Promise<number>;
  ggml_is_empty(arg0: bigint): Promise<number>;
  ggml_is_matrix(arg0: bigint): Promise<number>;
  ggml_is_numa(): Promise<number>;
  ggml_is_permuted(arg0: bigint): Promise<number>;
  ggml_is_quantized(arg0: number): Promise<number>;
  ggml_is_scalar(arg0: bigint): Promise<number>;
  ggml_is_transposed(arg0: bigint): Promise<number>;
  ggml_is_vector(arg0: bigint): Promise<number>;
  ggml_is_view(arg0: bigint): Promise<number>;
  ggml_n_dims(arg0: bigint): Promise<number>;
  ggml_nbytes(arg0: bigint): Promise<bigint>;
  ggml_nbytes_pad(arg0: bigint): Promise<bigint>;
  ggml_nelements(arg0: bigint): Promise<bigint>;
  ggml_nrows(arg0: bigint): Promise<bigint>;
  ggml_op_desc(arg0: bigint): Promise<bigint>;
  ggml_op_name(arg0: number): Promise<bigint>;
  ggml_op_symbol(arg0: number): Promise<bigint>;
  ggml_quantize_requires_imatrix(arg0: number): Promise<number>;
  ggml_row_size(arg0: number, arg1: bigint): Promise<bigint>;
  ggml_set_abort_callback(arg0: bigint): Promise<bigint>;
  ggml_status_to_string(arg0: number): Promise<bigint>;
  ggml_tensor_overhead(): Promise<bigint>;
  ggml_type_name(arg0: number): Promise<bigint>;
  ggml_type_size(arg0: number): Promise<bigint>;
  ggml_unary_op_name(arg0: number): Promise<bigint>;
  ggml_validate_row_data(arg0: number, arg1: bigint, arg2: bigint): Promise<number>;
  ggml_version(): Promise<bigint>;
  gguf_find_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_find_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_free(arg0: bigint): Promise<void>;
  gguf_get_alignment(arg0: bigint): Promise<bigint>;
  gguf_get_arr_data(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_arr_n(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_arr_str(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  gguf_get_arr_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_data_offset(arg0: bigint): Promise<bigint>;
  gguf_get_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_kv_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_meta_data(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_get_meta_size(arg0: bigint): Promise<bigint>;
  gguf_get_n_kv(arg0: bigint): Promise<bigint>;
  gguf_get_n_tensors(arg0: bigint): Promise<bigint>;
  gguf_get_tensor_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_ne(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_offset(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_bool(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_data(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_f32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_f64(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i16(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i64(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_i8(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_str(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_u16(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_u32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_u64(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_u8(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_version(arg0: bigint): Promise<number>;
  gguf_init_empty(): Promise<bigint>;
  gguf_init_from_buffer(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  gguf_init_from_callback(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  gguf_init_from_file(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_type_name(arg0: number): Promise<bigint>;
  load_imatrix(arg0: bigint): Promise<number>;
  new_adetailer_ctx(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<bigint>;
  new_sd_ctx(arg0: bigint): Promise<bigint>;
  new_upscaler_ctx(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: bigint, arg5: bigint): Promise<bigint>;
  preprocess_canny(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Promise<number>;
  save_imatrix(arg0: bigint): Promise<void>;
  sd_cache_params_init(arg0: bigint): Promise<void>;
  sd_cancel_generation(arg0: bigint, arg1: number): Promise<void>;
  sd_commit(): Promise<bigint>;
  sd_ctx_get_memory_info(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  sd_ctx_get_params(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  sd_ctx_get_runtime_info(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  sd_ctx_has_control_net(arg0: bigint): Promise<number>;
  sd_ctx_load_control_net(arg0: bigint, arg1: bigint): Promise<number>;
  sd_ctx_params_init(arg0: bigint): Promise<void>;
  sd_ctx_params_to_str(arg0: bigint): Promise<bigint>;
  sd_ctx_supports_image_generation(arg0: bigint): Promise<number>;
  sd_ctx_supports_video_generation(arg0: bigint): Promise<number>;
  sd_ctx_unload_control_net(arg0: bigint): Promise<number>;
  sd_get_default_sample_method(arg0: bigint): Promise<number>;
  sd_get_default_scheduler(arg0: bigint, arg1: number): Promise<number>;
  sd_get_model_version_name(arg0: bigint): Promise<bigint>;
  sd_get_num_physical_cores(): Promise<number>;
  sd_get_system_info(): Promise<bigint>;
  sd_hires_params_init(arg0: bigint): Promise<void>;
  sd_hires_upscaler_name(arg0: number): Promise<bigint>;
  sd_img_gen_params_init(arg0: bigint): Promise<void>;
  sd_img_gen_params_to_str(arg0: bigint): Promise<bigint>;
  sd_list_devices(arg0: bigint, arg1: bigint): Promise<bigint>;
  sd_lora_apply_mode_name(arg0: number): Promise<bigint>;
  sd_prediction_name(arg0: number): Promise<bigint>;
  sd_preview_name(arg0: number): Promise<bigint>;
  sd_rng_type_name(arg0: number): Promise<bigint>;
  sd_sample_method_name(arg0: number): Promise<bigint>;
  sd_sample_params_init(arg0: bigint): Promise<void>;
  sd_sample_params_to_str(arg0: bigint): Promise<bigint>;
  sd_scheduler_name(arg0: number): Promise<bigint>;
  sd_set_backend_eval_callback(arg0: bigint, arg1: bigint): Promise<void>;
  sd_set_log_callback(arg0: bigint, arg1: bigint): Promise<void>;
  sd_set_preview_callback(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: bigint): Promise<void>;
  sd_set_progress_callback(arg0: bigint, arg1: bigint): Promise<void>;
  sd_type_name(arg0: number): Promise<bigint>;
  sd_version(): Promise<bigint>;
  sd_vid_gen_params_init(arg0: bigint): Promise<void>;
  str_to_lora_apply_mode(arg0: bigint): Promise<number>;
  str_to_prediction(arg0: bigint): Promise<number>;
  str_to_preview(arg0: bigint): Promise<number>;
  str_to_rng_type(arg0: bigint): Promise<number>;
  str_to_sample_method(arg0: bigint): Promise<number>;
  str_to_scheduler(arg0: bigint): Promise<number>;
  str_to_sd_hires_upscaler(arg0: bigint): Promise<number>;
  str_to_sd_type(arg0: bigint): Promise<number>;
  upscale(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint): Promise<number>;
}
